language: ruby
cache: bundler
rvm:
  - 2.5.1
before_install: gem install bundler -v 1.16.3
notifications:
  email: false
script:
  - bundle exec rake rubocop
  - bundle exec rake spec

after_success:
  - bundle exec codeclimate-test-reporter
